### ISSUE TITLE
Test code sometimes crashes in rChangeCurrRing(ip_sring*)

### ISSUE THREAD

**Issue by tthsqe12** [tthsqe12/SingularInterpreter#13]
The following code is usual when one want's to use a ring R in libsingular.
```
S = currRing;
rChangeCurrRing(R);
...do your stuff with R...
rChangeCurrRing(S);   <----- crash here
```

The problem happens when somewhere someone does not follow this convention and leaves libsingular's currRing pointing to a ring R' after they are done. If R' gets gc'd the memory is junk and S now gets the junky ring R' in the above code. This crashes because rChangeCurrRing is a non-trivial function.

Are we able to always restore the currRing after using it? If not, then we have to forget about restoring it everywhere. This would lead to a another headache of determining if a function call is going to change the currRing.

ahh, singular's currRing........

**Comment by tthsqe12** [comment]
@rfourquet The current test code is sometimes crashing for this reason at least because of mstd
https://github.com/tthsqe12/SingularInterpreter/blob/master/test/ideal.sing#L14

**Comment by rfourquet** [comment]
Good catch! yes sorry, I have left a "TODO: clear_curr_ring later when possible" in the code and forgot about it. Will fix that now.
